### ISSUE TITLE
SAML/PEFIM proxy configuration: proxy must not try to validate attributes

### ISSUE THREAD

**Issue by rhoerbe** [its-dirg/IdProxy#3]
If COPY_ASSERTION = True + mandatory attributes (requestedAttribute/EntityCategory)
are configured  in SP metadata, this leads to the proxy checking for mandatory attributes. Consequently, the proxy raises an error for missing attribute, because it cannot decrypt the assertion.
Action: Make validation of attribute set optional

**Comment by HaToHo** [comment]
This configuration already exists. However I found an misspelling in the definition file  (/Users/haho0032/Develop/githubFork/pysaml2/src/saml2/attributemaps/saml_uri.py) for pvp-principalname, which will cause an error on almost the exact place in the code. You h have to regenerate the metadata xml file, to correct the issue. Have have not check in the correction yet.

The configuration to use is:
"fail_on_missing_requested": False,

```
        },
        "policy": {
            "default": {
                "lifetime": {"minutes": 15},
                "attribute_restrictions": None,  # means all I have
                "name_form": NAME_FORMAT_URI,
                "entity_categories": ["swamid", "edugain"],
                "fail_on_missing_requested": False,
            },
        },
```
