### ISSUE TITLE
SAML/PEFIM proxy config: nameid must be unencrypted

### ISSUE THREAD

**Issue by rhoerbe** [its-dirg/IdProxy#4]
PEFIM must have 2 assertions: one for NameID (targeted IDs) and one for attributes. Otherwise the proxy cannot make targeted ids for the SP.

(Limitation in saml2int - response.py/parse_assertion?)

**Comment by HaToHo** [comment]
In the new pefim_proxy and the updated pysaml2 version on my repo. NameId is now not encrypted and all attributes are encrypted and enclosed in the advice element. New issues should be added to pefim_proxy.
