### ISSUE TITLE
SAML/PEFIM: SP mapping

### ISSUE THREAD

**Issue by rhoerbe** [its-dirg/IdProxy#6]
Problem:
In PEFIM the proxy does not disclose the SP's identity to the IDP, but the affiliation to an entity categor (EC)  needs to be communicated. To support automated ARPs it is convenient to publish each group of application-side SPs with the same EC as a single IDP-side SP. 

The metadata for this SP would differ in the EC and in the entityID (which could have the EC concatenated).

**Comment by HaToHo** [comment]
Moved to the pefim_proxy.
