### ISSUE TITLE
Self-contained NS in encrypted assertion

### ISSUE THREAD

**Issue by rhoerbe** [its-dirg/IdProxy#8]
Encrypted assertion issued by the IDP must be self-contained with respect to XML namespaces. See the updated SAML PEFIM Profile V1.1

**Comment by HaToHo** [comment]
https://kantarainitiative.org/confluence/display/fiwg/PEFIM+SAML+profile

**Comment by HaToHo** [comment]
Added to pysaml2 on my local repo and tested in pefim proxy. If more issues is found on this issue, add it to pefim_proxy.
